name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build .

    - name: Test
      env:
        STORJ_SATELLITE: us-central-1.tardigrade.io:7777
        STORJ_API_KEY: ${{ secrets.STORJ_API_KEY }}
        STORJ_SECRET: ${{ secrets.STORJ_SECRET }}
      run: go test -v .
